# Generated by Django 5.2.4 on 2026-06-17 10:32

import projects.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(projects.constants.ProjectStatus['OPEN'], 'Open'), (projects.constants.ProjectStatus['CLOSED'], 'Closed')], default=projects.constants.ProjectStatus['OPEN'], max_length=6, verbose_name='Статус'),
        ),
    ]
